### ISSUE TITLE
re-create the DrEYEve dataset ground truth

### ISSUE THREAD

**Issue by MuhammadKA** [ndrplz/dreyeve#10]
I am trying to run the matlab codes to "re-create the DrEYEve dataset ground truth". However, I can't find the script_for_fixation_images.m
Can you please tell me where to find it

**Comment by ndrplz** [comment]
Hi @MuhammadKA, the script you mention shouldn't be necessary. You should be able to comment line 47 and use [`create_new_ground_truth` at line 46](https://github.com/ndrplz/dreyeve/blob/f3dd6da24578ce0ac60b5a9a1870767c2c6e5360/matlab/create_ground_truth/main.m#L46) instead.

**Comment by ykotseruba** [comment]
Hi, I am having a similar issue. The script `create_new_ground_truth.m` relies on precomputed homography data in the form of `gar_%06d_etg_%06d.mat`, which in turn requires sets of sift descriptors computed for each frame with VLFeat. I was able to reimplement the missing parts of code but I am not getting the same ground truth. Could you please make the code for homography calculation available as well? Perhaps, I am missing some parameter settings.
