### ISSUE TITLE
to compute optical flow matlab code

### ISSUE THREAD

**Issue by alaa2020osama** [ndrplz/dreyeve#11]
Undefined function or variable 'get_optical_flow'. 
Where could I find this function?

**Comment by ndrplz** [comment]
You can find it [here](https://github.com/ndrplz/dreyeve/blob/f3dd6da24578ce0ac60b5a9a1870767c2c6e5360/matlab/external_libs/OpticalFlow/get_optical_flow.m).

Next time please search what you're looking for in the repository search (top-left corner of the page) before opening new issues.
