### ISSUE TITLE
Coarse2FineTwoFrames.m source code

### ISSUE THREAD

**Issue by MuhammadKA** [ndrplz/dreyeve#12]
I am trying to convert the optical flow code to C/C++ code. However, the core of the code is Coarse2FineTwoFrames.m file which is written in C++ and only a mex file is used to call the function using matlab. 
Having this mex file makes Matlab coder unable to convert the code to C/C++ as it can not find the Coarse2FineTwoFrames function.

Can you please tell me how to get the Coarse2FineTwoFrames.m written completely in Matlab?

**Comment by ndrplz** [comment]
Hi @MuhammadKA , as you can see we relied on an external lib to compute the optical flow (we did not write that ourselves) so I don't think we can help you.

However, my feeling is that if you need an optical flow implementation in C/C++ you can probably find better off-the-shelf alternatives than trying to convert this Matlab library in C++.
