### ISSUE TITLE
SVISINIT problem

### ISSUE THREAD

**Issue by soniabaee** [ndrplz/dreyeve#13]
Hi all, 
I have a problem with running the test file `dreyeve/matlab/assessment/test/test_multifovea.m` to run on my data! but unfortunately, the SVISINIT keeps showing an error `too many input arguments` and when I've tried to debug it in the file it's saying don't edit the file which is apparently automatically generated. I don't know if I'm missing something or not. It would be great if you could direct me to solve this issue.

Thanks for your time!

**Comment by ndrplz** [comment]
The SVIS toolbox is an [external library](http://svi.cps.utexas.edu/software.shtml) we relied on to perform the perceptual experiments. We didn't write the code ourselves so I don't think I can be much helpful in the error is during toolbox initialization.

Did you try to run the [`svistest.m`](https://github.com/ndrplz/dreyeve/blob/master/matlab/external_libs/svistoolbox-1.0.5/svistest.m)?

**Comment by soniabaee** [comment]
That's so true and I knew it but I thought you had the same issue! Yes, I've tried that with no surprise I got the same error! which is for the function `svismex` and it says:

> too many input arguments.

Unfortunately, I couldn't find a way to communicate with their developer so far!
Anyway, Thanks so much!

**Comment by ndrplz** [comment]
I'm sorry I can't be more helpful. If you debug the problem, please update this thread so that it can possibly be helpful to a wider audience. Good luck!

**Comment by soniabaee** [comment]
No problem! Sure, thanks!

**Comment by ndrplz** [comment]
Closing. If you solved the issue at the end, feel free to drop a few lines here for posterity :)
