### ISSUE TITLE
Where can I get `dreyevenet_model_central_crop.h5` model

### ISSUE THREAD

**Issue by ndrplz** [ndrplz/dreyeve#15]
Thanks for clarifying the issue above. I have a new issue now. Where can I get `dreyevenet_model_central_crop.h5` model?

_Originally posted by @varunjammula in https://github.com/ndrplz/dreyeve/issues/5#issuecomment-656002720_

**Comment by ndrplz** [comment]
@varunjammula @DavideA 

As far as I remember we only released the weights for the multibranch model ([here](https://drive.google.com/open?id=1cS7VaguQCoqkZ5mHWO3zDj5mNlOY61bj)). I don't think the ones you mention are available anywhere.

**Comment by varunjammula** [comment]
Will you release them or do I have train a model to get those weights? Can you please let me know how I can do that!

**Comment by ndrplz** [comment]
Actually, now that i double-check the weights here might still be the right ones. Have you actually tried to load the weights linked above?

**Comment by varunjammula** [comment]
The above model works. Thanks for the information. You can close the issue now.
