### ISSUE TITLE
dreyeve_mean_frame.png

### ISSUE THREAD

**Issue by Tobias-Fischer** [ndrplz/dreyeve#17]
Hi there,
Is it possible to make the dreyeve_mean_frame.png file available?

Many thanks,
Tobias

**Comment by ndrplz** [comment]
Hi @Tobias-Fischer ,

unfortunately we don't have it at hand. Anyway, you should be able to compute it easily from the released data. Simply sum all images in the training set (make sure to cast to float first) and divide by the sum, and you're good to go :)
