### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by kj-kx** [ndrplz/dreyeve#19]
hello,could you tell me the meanning of "cineca",and if i should run matlab code  before semseg code to deal with DREYEVE_DATA?

**Comment by ndrplz** [comment]
Hi @kj-kx , could you please reformulate your question with a bit more context / details, possibly linking to the actual lines of code?

**Comment by kj-kx** [comment]
thank you for your reply,i download dataset from http://imagelab.ing.unimore.it/dreyeve ,then i just set dreyeve_dir = '/home/kj/DREYEVE_DATA' in ~/.dreyeve/experiments/config.py.
when i run train.py,error occurs.
ValueError: Provided path "/home/kj/DREYEVE_DATA/10/frames/003780.jpg" does NOT exist.
so,how should i deal with the dataset before train?

**Comment by kj-kx** [comment]
hello，the question has been asked before，i can find solution from prior message.
thank you for you share

**Comment by ndrplz** [comment]
Great that you found a solution.
