### ISSUE TITLE
Saliency map and saliency_fix map files could not be found

### ISSUE THREAD

**Issue by YanDingXin** [ndrplz/dreyeve#6]
Hi，excuse me.The saliency map and saliency_fix map files are used in the predict_dreyeve_sequence. Py project.I hope you can reply after reading it. Thank you very much.

`_
    I_ff[0, :, 0, :, :] = x
    OF_ff[0, :, 0, :, :] = of
    SEG_ff[0, :, 0, :, :] = seg

    Y_sal[0, 0] = read_image(join(sequence_dir, 'saliency', '{:06d}.png'.format(sample)), channels_first=False,
                             color=False, resize_dim=(h, w))
    Y_fix[0, 0] = read_image(join(sequence_dir, 'saliency_fix', '{:06d}.png'.format(sample)), channels_first=False,
                             color=False, resize_dim=(h, w))

    return [I_ff, I_s, I_c, OF_ff, OF_s, OF_c, SEG_ff, SEG_s, SEG_c], [Y_sal, Y_fix]
_`

those code come from predict_dreyeve_sequence.py.

**Comment by DavideA** [comment]
Hi and thank you for interest.

What is referred to as saliency is the first version of the groundtruth maps, created as described in the [first workshop paper](https://iris.unimore.it/retrieve/handle/11380/1104385/78285/Alletto_DREyeVe_A_Dataset_CVPR_2016_paper.pdf).

In the [journal paper](https://arxiv.org/abs/1705.03854), we relied on a slightly different procedure to build a fixation map for a frame. This is what is referred to as `saliency_fix` in the code. Basically, everything that has the `_fix` postfix identifies such "new" fixation maps. 

We consider the latter one (`fix`) the proper groundtruth annotation of our dataset. You are strongly encouraged to rely on it for the evaluation of your method. 
The `saliency` version should only be used to reproduce results in our[ conference paper](https://arxiv.org/abs/1611.08215).

Hope this helps,
D

**Comment by YanDingXin** [comment]
> Hi and thank you for your interest.
> What is referred to as saliency is the first version of the ground truth maps, created as described in the first workshop paper.
> In the journal paper, we relied on a slightly different procedure to build a fixation map for a frame. This is what is referred to as saliency_fix in the code. Basically, everything that has the _fix postfix identifies such "new" fixation maps.
> We consider the latter one (fix) the proper ground truth annotation of our dataset. You are strongly encouraged to rely on it for the evaluation of your method.
> The saliency version should only be used to reproduce results in our conference paper.
> Edit: the fixation videos you get once you download the dataset are relative to the fix ground truth. So, you should only unroll them into the saliency_fix folder and comment out the lines loading from the saliency folder. Indeed, the variable Y_sal in the lines you mentioned should not be used for training at all.
> Hope this helps,
> D

Well, thank you very much for your quick reply, which has helped me a lot.I will continue to try to implement this experiment.Thanks again.

**Comment by varunjammula** [comment]
Hi, how do I compute the saliency_fix images? I could not find the code to get these frames. Can you please let me know how to fix this? Thanks!
