### ISSUE TITLE
frames extraction and path error

### ISSUE THREAD

**Issue by alaa2020osama** [ndrplz/dreyeve#9]
I am trying to implement your code but it gives the following error:
File "/content/drive/My Drive/computer_vision_utils/io_helper.py", line 33, in read_image
    raise ValueError('Provided path "{}" does NOT exist.'.format(img_path)) ######1
ValueError: Provided path "/content/drive/My Drive/DREYEVE Unzipped/29/frames/004126.jpg" does NOT exist.
I checked the folders myself self and there is no created folder called frames and I didn't find this folder or the images in any other directory. I wonder if there is a missing code part that extracts frames from the videos and creates that missing path?

**Comment by ndrplz** [comment]
Hi @alaa2020osama, could you please provide the whole error stacktrace to understand better where is the origin of the problem?

Anyway you're right, I assume that there is a missing piece of code which creates those `frames` folders and unrolles the dataset videos there. You should be able to do that yourself with a few lines of python / bash and [ffmpeg](https://www.ffmpeg.org/).
